package com.tian.mybatis.model;

import java.util.Date;

public class PaySet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.id
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.token
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.pc_type
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private String pcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.pc_name
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private String pcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.seller_email
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private String sellerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.key
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.partner
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private String partner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.pc_order
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private Integer pcOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_set.create_time
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.id
     *
     * @return the value of pay_set.id
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.id
     *
     * @param id the value for pay_set.id
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.token
     *
     * @return the value of pay_set.token
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.token
     *
     * @param token the value for pay_set.token
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.pc_type
     *
     * @return the value of pay_set.pc_type
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public String getPcType() {
        return pcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.pc_type
     *
     * @param pcType the value for pay_set.pc_type
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setPcType(String pcType) {
        this.pcType = pcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.pc_name
     *
     * @return the value of pay_set.pc_name
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public String getPcName() {
        return pcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.pc_name
     *
     * @param pcName the value for pay_set.pc_name
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setPcName(String pcName) {
        this.pcName = pcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.seller_email
     *
     * @return the value of pay_set.seller_email
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.seller_email
     *
     * @param sellerEmail the value for pay_set.seller_email
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.key
     *
     * @return the value of pay_set.key
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.key
     *
     * @param key the value for pay_set.key
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.partner
     *
     * @return the value of pay_set.partner
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.partner
     *
     * @param partner the value for pay_set.partner
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setPartner(String partner) {
        this.partner = partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.pc_order
     *
     * @return the value of pay_set.pc_order
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public Integer getPcOrder() {
        return pcOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.pc_order
     *
     * @param pcOrder the value for pay_set.pc_order
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setPcOrder(Integer pcOrder) {
        this.pcOrder = pcOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_set.create_time
     *
     * @return the value of pay_set.create_time
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_set.create_time
     *
     * @param createTime the value for pay_set.create_time
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}