package com.tian.mybatis.model;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USERNAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.TRUE_NAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UNIT_CODE
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String unitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UNIT_NAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_TYPE
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.POLICE_ID
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String policeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.OPEN_FLAG
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String openFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REMARK
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.DELETEFLAG
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.SECRECY
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String secrecy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.CREATE_USER
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.CREATE_DATETIME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UPDATE_USER
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UPDATE_DATETIME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV1
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV2
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV3
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV4
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV5
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV6
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV7
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.REV8
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    private String rev8;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.ID
     *
     * @return the value of SYS_USER.ID
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.ID
     *
     * @param id the value for SYS_USER.ID
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USERNAME
     *
     * @return the value of SYS_USER.USERNAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USERNAME
     *
     * @param username the value for SYS_USER.USERNAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PASSWORD
     *
     * @return the value of SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PASSWORD
     *
     * @param password the value for SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.TRUE_NAME
     *
     * @return the value of SYS_USER.TRUE_NAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.TRUE_NAME
     *
     * @param trueName the value for SYS_USER.TRUE_NAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.UNIT_CODE
     *
     * @return the value of SYS_USER.UNIT_CODE
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.UNIT_CODE
     *
     * @param unitCode the value for SYS_USER.UNIT_CODE
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.UNIT_NAME
     *
     * @return the value of SYS_USER.UNIT_NAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.UNIT_NAME
     *
     * @param unitName the value for SYS_USER.UNIT_NAME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_TYPE
     *
     * @return the value of SYS_USER.USER_TYPE
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_TYPE
     *
     * @param userType the value for SYS_USER.USER_TYPE
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.POLICE_ID
     *
     * @return the value of SYS_USER.POLICE_ID
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getPoliceId() {
        return policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.POLICE_ID
     *
     * @param policeId the value for SYS_USER.POLICE_ID
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setPoliceId(String policeId) {
        this.policeId = policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.OPEN_FLAG
     *
     * @return the value of SYS_USER.OPEN_FLAG
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getOpenFlag() {
        return openFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.OPEN_FLAG
     *
     * @param openFlag the value for SYS_USER.OPEN_FLAG
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setOpenFlag(String openFlag) {
        this.openFlag = openFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REMARK
     *
     * @return the value of SYS_USER.REMARK
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REMARK
     *
     * @param remark the value for SYS_USER.REMARK
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.DELETEFLAG
     *
     * @return the value of SYS_USER.DELETEFLAG
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.DELETEFLAG
     *
     * @param deleteflag the value for SYS_USER.DELETEFLAG
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.SECRECY
     *
     * @return the value of SYS_USER.SECRECY
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getSecrecy() {
        return secrecy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.SECRECY
     *
     * @param secrecy the value for SYS_USER.SECRECY
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setSecrecy(String secrecy) {
        this.secrecy = secrecy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.CREATE_USER
     *
     * @return the value of SYS_USER.CREATE_USER
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.CREATE_USER
     *
     * @param createUser the value for SYS_USER.CREATE_USER
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.CREATE_DATETIME
     *
     * @return the value of SYS_USER.CREATE_DATETIME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.CREATE_DATETIME
     *
     * @param createDatetime the value for SYS_USER.CREATE_DATETIME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.UPDATE_USER
     *
     * @return the value of SYS_USER.UPDATE_USER
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.UPDATE_USER
     *
     * @param updateUser the value for SYS_USER.UPDATE_USER
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.UPDATE_DATETIME
     *
     * @return the value of SYS_USER.UPDATE_DATETIME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.UPDATE_DATETIME
     *
     * @param updateDatetime the value for SYS_USER.UPDATE_DATETIME
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV1
     *
     * @return the value of SYS_USER.REV1
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev1() {
        return rev1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV1
     *
     * @param rev1 the value for SYS_USER.REV1
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev1(String rev1) {
        this.rev1 = rev1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV2
     *
     * @return the value of SYS_USER.REV2
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev2() {
        return rev2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV2
     *
     * @param rev2 the value for SYS_USER.REV2
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev2(String rev2) {
        this.rev2 = rev2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV3
     *
     * @return the value of SYS_USER.REV3
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev3() {
        return rev3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV3
     *
     * @param rev3 the value for SYS_USER.REV3
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev3(String rev3) {
        this.rev3 = rev3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV4
     *
     * @return the value of SYS_USER.REV4
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev4() {
        return rev4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV4
     *
     * @param rev4 the value for SYS_USER.REV4
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev4(String rev4) {
        this.rev4 = rev4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV5
     *
     * @return the value of SYS_USER.REV5
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev5() {
        return rev5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV5
     *
     * @param rev5 the value for SYS_USER.REV5
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev5(String rev5) {
        this.rev5 = rev5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV6
     *
     * @return the value of SYS_USER.REV6
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev6() {
        return rev6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV6
     *
     * @param rev6 the value for SYS_USER.REV6
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev6(String rev6) {
        this.rev6 = rev6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV7
     *
     * @return the value of SYS_USER.REV7
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev7() {
        return rev7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV7
     *
     * @param rev7 the value for SYS_USER.REV7
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev7(String rev7) {
        this.rev7 = rev7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.REV8
     *
     * @return the value of SYS_USER.REV8
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public String getRev8() {
        return rev8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.REV8
     *
     * @param rev8 the value for SYS_USER.REV8
     *
     * @mbggenerated Tue Aug 19 10:31:44 CST 2014
     */
    public void setRev8(String rev8) {
        this.rev8 = rev8;
    }
}