package com.tian.mybatis.dao;

import com.tian.mybatis.model.PaySet;
import com.tian.mybatis.model.PaySetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaySetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int countByExample(PaySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int deleteByExample(PaySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int insert(PaySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int insertSelective(PaySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    List<PaySet> selectByExample(PaySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    PaySet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") PaySet record, @Param("example") PaySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int updateByExample(@Param("record") PaySet record, @Param("example") PaySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int updateByPrimaryKeySelective(PaySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_set
     *
     * @mbggenerated Mon Aug 18 23:14:42 CST 2014
     */
    int updateByPrimaryKey(PaySet record);
}